[2024-08-13T08:52:51.924+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T08:52:51.933+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-13T08:52:51.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-13T08:52:51.939+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-13T08:52:51.956+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): is_file_in_s3> on 2024-08-12 00:00:00+00:00
[2024-08-13T08:52:51.960+0000] {standard_task_runner.py:64} INFO - Started process 17812 to run task
[2024-08-13T08:52:51.962+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'is_file_in_s3', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmp6u7jcz5d']
[2024-08-13T08:52:51.964+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask is_file_in_s3
[2024-08-13T08:52:52.004+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 scheduled__2024-08-12T00:00:00+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-13T08:52:52.082+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='is_file_in_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T00:00:00+00:00'
[2024-08-13T08:52:52.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T08:52:52.094+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-13T08:52:52.094+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_13082024085242.csv
[2024-08-13T08:52:52.099+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-08-13T08:52:52.100+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-13T08:52:57.442+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_13082024085242.csv
[2024-08-13T08:53:02.450+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_13082024085242.csv
[2024-08-13T08:53:02.462+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-08-13T08:53:02.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T08:53:02.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Zillow_Analytics_DAG, task_id=is_file_in_s3, run_id=scheduled__2024-08-12T00:00:00+00:00, execution_date=20240812T000000, start_date=20240813T085251, end_date=20240813T085302
[2024-08-13T08:53:02.506+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-13T08:53:02.521+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-13T08:53:02.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
